---
apiVersion: v1
kind: Namespace
metadata:
  name: fakelogs
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fakelogs-config
  namespace: fakelogs
data:
  config.yaml: |
    --- 
    patterns:
      - '{"name":"{username}", "age":"{int}", "Moto": "{sentence}", "Summary": "{paragraph}", "ip_addr": "{ipv4}", "email": "{email}", "timestamp":"{ts_rfc3389}"}'
    eps: 0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fakelogs-deployment
  namespace: fakelogs
  labels:
    app: fakelogs
spec:
  replicas: 6
  selector:
    matchLabels:
      app: fakelogs
  template:
    metadata:
      labels:
        app: fakelogs
    spec:
      containers:
      - name: fakelogs
        image: fakelogs:t
        args: ["generate","-c","/data/config.yaml"]
        volumeMounts:
        - name: config
          mountPath: "/data/"
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: fakelogs-config
          # An array of keys from the ConfigMap to create as files
          items:
          - key: "config.yaml"
            path: "config.yaml"
