name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Build
      run: cargo build --release --verbose
    - name: Run tests
      run: cargo test
    - name: Run help
      run: ./target/release/fakelogs --help
    - name: Run benchmark
      run: ./target/release/fakelogs benchmark -c example/fakejson.yaml
    - name: Store executable as artefact
      uses: actions/upload-artifact@v2
      with:
        name: fakelogs-executable
        path: target/release/fakelogs